"""Remove only interpreter-generated bytecode from an immutable runtime."""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import TYPE_CHECKING, Never

from scripts.cache_types import CacheIdentity, identity
from scripts.install_errors import InstallPluginError

if TYPE_CHECKING:
    from pathlib import Path

    from scripts.runtime_tree import RuntimeTreeManifest

_INVALID = "portable_runtime_invalid"


@dataclass(frozen=True, slots=True)
class _Extra:
    path: Path
    relative: str
    identity: CacheIdentity


def remove_generated_bytecode(root: Path, manifest: RuntimeTreeManifest) -> bool:
    """Remove a complete safe ``__pycache__`` delta and nothing else."""
    try:
        root_before = identity(root.lstat())
        files, directories, compatible = _extras(root, manifest)
        if not compatible or (not files and not directories):
            return False
        if not _repairable(files, directories, manifest):
            return False
        for extra in files:
            _require_unchanged(extra, directory=False)
            extra.path.unlink()
        for extra in sorted(directories, key=lambda item: len(item.path.parts), reverse=True):
            _require_unchanged(extra, directory=True)
            extra.path.rmdir()
        if identity(root.lstat()) != root_before:
            _fail()
    except InstallPluginError:
        raise
    except OSError as error:
        raise InstallPluginError(_INVALID) from error
    return True


def _extras(
    root: Path,
    manifest: RuntimeTreeManifest,
) -> tuple[tuple[_Extra, ...], tuple[_Extra, ...], bool]:
    expected_files = {entry.path for entry in manifest.entries if entry.type == "file"}
    expected_directories = {entry.path for entry in manifest.entries if entry.type == "directory"}
    files: list[_Extra] = []
    directories: list[_Extra] = []
    stack = [root]
    compatible = True
    while stack:
        current = stack.pop()
        with os.scandir(current) as iterator:
            for entry in iterator:
                path = current / entry.name
                metadata = path.lstat()
                _require_direct(metadata)
                relative = path.relative_to(root).as_posix()
                if stat.S_ISDIR(metadata.st_mode):
                    compatible &= relative not in expected_files
                    if relative not in expected_directories:
                        directories.append(_Extra(path, relative, identity(metadata)))
                    stack.append(path)
                elif stat.S_ISREG(metadata.st_mode):
                    compatible &= relative not in expected_directories
                    if relative not in expected_files:
                        files.append(_Extra(path, relative, identity(metadata)))
                else:
                    _fail()
    return tuple(files), tuple(directories), compatible


def _repairable(
    files: tuple[_Extra, ...],
    directories: tuple[_Extra, ...],
    manifest: RuntimeTreeManifest,
) -> bool:
    expected_directories = {entry.path for entry in manifest.entries if entry.type == "directory"}
    extra_directories = {extra.relative for extra in directories}
    for extra in directories:
        relative = PurePosixPath(extra.relative)
        parent = relative.parent.as_posix()
        if relative.name != "__pycache__" or parent not in {*expected_directories, "."}:
            return False
    for extra in files:
        relative = PurePosixPath(extra.relative)
        if (
            relative.suffix != ".pyc"
            or relative.parent.name != "__pycache__"
            or relative.parent.as_posix() not in extra_directories
        ):
            return False
    return True


def _require_unchanged(extra: _Extra, *, directory: bool) -> None:
    metadata = extra.path.lstat()
    _require_direct(metadata)
    if stat.S_ISDIR(metadata.st_mode) is not directory or identity(metadata) != extra.identity:
        _fail()


def _require_direct(metadata: os.stat_result) -> None:
    reparse = getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0)
    if (
        stat.S_ISLNK(metadata.st_mode)
        or getattr(metadata, "st_file_attributes", 0) & reparse
        or (stat.S_ISREG(metadata.st_mode) and metadata.st_nlink != 1)
    ):
        _fail()


def _fail() -> Never:
    raise InstallPluginError(_INVALID)
